#!/usr/bin/env python3
"""Regenerate photography/photos.js from the images in photography/photos/.

Drop photographs into that folder, run

    python3 build_photography.py

and the gallery picks them up. Pixel dimensions are read straight out of each
file's header -- no Pillow, no dependencies -- so the page can reserve the right
shape for every frame before a single byte of image data arrives, and nothing
jumps around as the gallery loads.

Two things in the manifest are yours to set by hand, and both survive a re-run:

  captions   add a "caption" to any entry and it is carried across
  order      the gallery shows photographs in manifest order, so reordering the
             lines reorders the page; anything new is appended at the end

Everything else -- which files exist, how big they are -- is read from the folder
each time.

Two things it will nag you about, both for the same reason the camera original of
nathan.jpg is kept out of the repository: files straight off a camera are large,
and they carry EXIF -- including, often, the GPS coordinates of where you were
standing. Export web-sized copies with the metadata stripped.
"""

from __future__ import annotations

import json
import re
import struct
import sys
from pathlib import Path
from urllib.parse import quote

PAGE = Path(__file__).parent / "photography"
FOLDER = PAGE / "photos"
MANIFEST = PAGE / "photos.js"
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".heic"}

HEADER = """\
/* The gallery manifest -- generated by build_photography.py from the images in
   photos/. Regenerate after adding or removing photographs:

     python3 build_photography.py

   from the repository root. Captions and the order of these lines are yours to
   set by hand; both are carried across a re-run, and new photographs are
   appended at the end. */

window.PHOTOS = [
"""


# --- reading dimensions out of image headers --------------------------------

def jpeg_size(f) -> tuple[int, int] | None:
    """Walk the marker segments to the start-of-frame, which carries the size."""
    f.seek(2)  # past SOI
    while True:
        marker = f.read(2)
        if len(marker) < 2 or marker[0] != 0xFF:
            return None
        kind = marker[1]
        (length,) = struct.unpack(">H", f.read(2))
        # Every SOFn but the four that are not frame headers (DHT, JPGA, DAC,
        # and the restart-interval marker) begins with precision, height, width.
        if kind in range(0xC0, 0xD0) and kind not in (0xC4, 0xC8, 0xCC):
            height, width = struct.unpack(">HH", f.read(5)[1:])
            return width, height
        f.seek(length - 2, 1)


def png_size(f) -> tuple[int, int] | None:
    f.seek(16)  # past signature, IHDR length, and IHDR type
    data = f.read(8)
    return struct.unpack(">II", data) if len(data) == 8 else None


def gif_size(f) -> tuple[int, int] | None:
    f.seek(6)
    data = f.read(4)
    return struct.unpack("<HH", data) if len(data) == 4 else None


def webp_size(f) -> tuple[int, int] | None:
    f.seek(12)
    chunk = f.read(4)
    if chunk == b"VP8X":
        f.seek(4 + 4, 1)  # chunk length, then the flags and reserved bytes
        raw = f.read(6)
        if len(raw) < 6:
            return None
        width = raw[0] | raw[1] << 8 | raw[2] << 16
        height = raw[3] | raw[4] << 8 | raw[5] << 16
        return width + 1, height + 1
    if chunk == b"VP8 ":
        f.seek(4 + 6, 1)  # chunk length, then the frame tag and sync code
        raw = f.read(4)
        if len(raw) < 4:
            return None
        width, height = struct.unpack("<HH", raw)
        return width & 0x3FFF, height & 0x3FFF
    if chunk == b"VP8L":
        f.seek(4 + 1, 1)  # chunk length, then the signature byte
        raw = f.read(4)
        if len(raw) < 4:
            return None
        (bits,) = struct.unpack("<I", raw)
        return (bits & 0x3FFF) + 1, ((bits >> 14) & 0x3FFF) + 1
    return None


def dimensions(path: Path) -> tuple[int, int] | None:
    """Best effort. Formats we cannot parse simply go in without a size."""
    try:
        with path.open("rb") as f:
            head = f.read(12)
            if head[:2] == b"\xff\xd8":
                return jpeg_size(f)
            if head[:8] == b"\x89PNG\r\n\x1a\n":
                return png_size(f)
            if head[:3] == b"GIF":
                return gif_size(f)
            if head[:4] == b"RIFF" and head[8:12] == b"WEBP":
                return webp_size(f)
    except (OSError, struct.error):
        pass
    return None


# --- what the last manifest said ---------------------------------------------

def previous() -> tuple[dict[str, str], list[str]]:
    """The captions and the running order from the current manifest, if any.

    Both are things a person edits by hand, so a re-run has to give them back
    rather than flattening them into whatever order the folder happens to be in.
    """
    if not MANIFEST.exists():
        return {}, []
    text = MANIFEST.read_text(encoding="utf-8")
    captions, order = {}, []
    for entry in re.findall(r"\{[^{}]*\}", text):
        src = re.search(r'"src"\s*:\s*"((?:[^"\\]|\\.)*)"', entry)
        if not src:
            continue
        name = json.loads(f'"{src.group(1)}"')
        order.append(name)
        caption = re.search(r'"caption"\s*:\s*"((?:[^"\\]|\\.)*)"', entry)
        if caption:
            captions[name] = json.loads(f'"{caption.group(1)}"')
    return captions, order


# --- ordering ----------------------------------------------------------------

def natural_key(path: Path):
    """So IMG_9 lands before IMG_10, the way a person would file them."""
    return [int(p) if p.isdigit() else p.lower() for p in re.split(r"(\d+)", path.name)]


def web_path(path: Path) -> str:
    """The src the page will use. Spaces and the like have to be escaped: this
    goes into an href, not onto a filesystem."""
    return "photos/" + quote(path.name)


def main() -> int:
    if not FOLDER.is_dir():
        print(f"No {FOLDER} folder to read.", file=sys.stderr)
        return 1

    files = sorted(
        (p for p in FOLDER.iterdir()
         if p.is_file() and p.suffix.lower() in EXTENSIONS and not p.name.startswith(".")),
        key=natural_key,
    )

    captions, order = previous()

    # Photographs already in the manifest keep the position they were given;
    # the rest follow, newest arrivals at the end.
    rank = {name: i for i, name in enumerate(order)}
    files.sort(key=lambda p: rank.get(web_path(p), len(rank)))

    lines, unsized, heavy = [], [], []

    for path in files:
        src = web_path(path)
        entry = {"src": src}
        size = dimensions(path)
        if size:
            entry["width"], entry["height"] = size
        else:
            unsized.append(path.name)
        if captions.get(src):
            entry["caption"] = captions[src]
        if path.stat().st_size > 2_000_000:
            heavy.append((path.name, path.stat().st_size / 1_000_000))
        lines.append("  " + json.dumps(entry, ensure_ascii=False) + ",")

    MANIFEST.write_text(HEADER + "\n".join(lines) + ("\n" if lines else "") + "];\n",
                        encoding="utf-8")

    print(f"{len(files)} photograph{'' if len(files) == 1 else 's'} -> {MANIFEST}")
    if unsized:
        print("  no dimensions readable, so these will settle into place as they "
              "load rather than holding their space: " + ", ".join(unsized))
    if heavy:
        print("  large enough to be worth exporting smaller, and worth checking "
              "for EXIF: " + ", ".join(f"{n} ({mb:.1f} MB)" for n, mb in heavy))
    kept = sum(1 for p in files if captions.get(web_path(p)))
    if kept:
        print(f"  kept {kept} caption{'' if kept == 1 else 's'}")
    total = sum(p.stat().st_size for p in files) / 1_000_000
    print(f"  {total:.0f} MB in the folder")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
