/* The gallery manifest -- generated by build_photography.py from the images in
   photos/. Regenerate after adding or removing photographs:

     python3 optimize_photography.py

   from the repository root, which makes the web copies and then rebuilds this.
   Captions and the order of these lines are yours to set by hand; both are
   carried across a re-run, and new photographs are appended at the end.

   `sources` is the ladder of copies that exist for a photograph, per format.
   photography.js turns each one into a srcset, so the browser downloads the one
   size and format it is about to draw rather than the largest one there is.
   `width` and `height` are the original's, and are only ever used as a shape. */

window.PHOTOS = [
  {"name": "0", "width": 3376, "height": 6000, "sources": {"avif": [400, 800, 1200, 1800, 2161], "webp": [400, 800, 1200, 1800, 2161], "jpg": [800, 1800]}, "color": "#706d47"},
  {"name": "1", "width": 3840, "height": 2160, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#505757"},
  {"name": "3", "width": 3840, "height": 2160, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#353f43"},
  {"name": "4", "width": 3840, "height": 2160, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#533838"},
  {"name": "6-2", "width": 3840, "height": 2160, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#52553b"},
  {"name": "6", "width": 3840, "height": 2160, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#25301e"},
  {"name": "dji-20250602195448-0082-d", "width": 2224, "height": 3953, "sources": {"avif": [400, 800, 1200, 1800, 2160], "webp": [400, 800, 1200, 1800, 2160], "jpg": [800, 1800]}, "color": "#5d5b5e"},
  {"name": "dsc04231-2", "width": 3480, "height": 6192, "sources": {"avif": [400, 800, 1200, 1800, 2158], "webp": [400, 800, 1200, 1800, 2158], "jpg": [800, 1800]}, "color": "#626767"},
  {"name": "dsc04336", "width": 3480, "height": 6192, "sources": {"avif": [400, 800, 1200, 1800, 2158], "webp": [400, 800, 1200, 1800, 2158], "jpg": [800, 1800]}, "color": "#686151"},
  {"name": "img-5387", "width": 1445, "height": 2174, "sources": {"avif": [400, 800, 1200, 1445], "webp": [400, 800, 1200, 1445], "jpg": [800]}, "color": "#9e8f6d"},
  {"name": "rahhhh", "width": 6123, "height": 3444, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#79765b"},
  {"name": "sun-rays", "width": 3840, "height": 2160, "sources": {"avif": [400, 800, 1200, 1800, 2400, 3200, 3840], "webp": [400, 800, 1200, 1800, 2400, 3200, 3840], "jpg": [800, 1800, 2400]}, "color": "#2b331c"},
  {"name": "sunset", "width": 3483, "height": 6192, "sources": {"avif": [400, 800, 1200, 1800, 2160], "webp": [400, 800, 1200, 1800, 2160], "jpg": [800, 1800]}, "color": "#755731"},
];
