/* The gallery manifest -- generated by build_photography.py from the images in
   photos/. Regenerate after adding or removing photographs:

     python3 build_photography.py

   from the repository root. Captions and the order of these lines are yours to
   set by hand; both are carried across a re-run, and new photographs are
   appended at the end. */

window.PHOTOS = [
  {"src": "photos/0.jpg", "width": 1350, "height": 2400},
  {"src": "photos/1.jpg", "width": 2400, "height": 1350},
  {"src": "photos/3.jpg", "width": 2400, "height": 1350},
  {"src": "photos/4.jpg", "width": 2400, "height": 1350},
  {"src": "photos/6%202.jpg", "width": 2400, "height": 1350},
  {"src": "photos/6.jpg", "width": 2400, "height": 1350},
  {"src": "photos/DJI_20250602195448_0082_D.jpg", "width": 1350, "height": 2400},
  {"src": "photos/DSC04231-2.jpg", "width": 1349, "height": 2400},
  {"src": "photos/DSC04336.jpg", "width": 1349, "height": 2400},
  {"src": "photos/IMG_5387.jpg", "width": 1595, "height": 2400},
  {"src": "photos/RAHHHH.jpg", "width": 2400, "height": 1350},
  {"src": "photos/Sun%20Rays.jpg", "width": 2400, "height": 1350},
  {"src": "photos/Sunset.jpg", "width": 1350, "height": 2400},
];
